insert into library values (1, 'learn java, learn scala, learn AWS','Technology library');
insert into library values (2, 'Mars Red Planet, Titan with water','Space Library');
insert into library values (3, '','Animal library');
insert into library values (4, '','Cloud Library');
insert into library values (5, 'Yellow Sun, Blue star, Red star','Star Library');
insert into library values (6, 'Life of tommy, Life of Brownie','Dogs Library');
insert into library values (7, 'xyz, abc, efg','A Library');
insert into library values (8, 'xyz, abc, efg','B Library');
insert into library values (9, 'xyz, abc, efg','D Library');
insert into library values (10, 'xyz, abc, efg','C Library');
